name: Langscape
packages:
  DesignSystem:
    path: DesignSystem
  UIComponents:
    path: UIComponents
  Utilities:
    path: Utilities
  DetectionKit:
    path: DetectionKit
  GameKitLS:
    path: GameKitLS
  VocabStore:
    path: VocabStore
  LLMKit:
    path: LLMKit

targets:
  Langscape:
    type: application
    platform: iOS
    sources:
      - LangscapeApp/Sources/LangscapeApp
    postBuildScripts:
      - name: Copy .env (Debug only)
        script: |
          if [ "${CONFIGURATION}" != "Debug" ]; then
            exit 0
          fi

          SRC="${SRCROOT}/.env"
          if [ ! -f "${SRC}" ]; then
            echo "warning: .env not found at ${SRC} (GEMINI_API_KEY will be unavailable)"
            exit 0
          fi

          DEST_DIR="${TARGET_BUILD_DIR}/${FULL_PRODUCT_NAME}"
          mkdir -p "${DEST_DIR}"
          cp "${SRC}" "${DEST_DIR}/.env"
          echo "Copied .env into app bundle."
        basedOnDependencyAnalysis: false
    info:
      path: LangscapeApp/Info.plist
      properties:
        CFBundleShortVersionString: '$(MARKETING_VERSION)'
        CFBundleVersion: '$(CURRENT_PROJECT_VERSION)'
        LSRequiresIPhoneOS: true
        NSCameraUsageDescription: We use your camera to interact with real-world objects. No photos are stored.
        UILaunchScreen: {}
    dependencies:
      - package: DesignSystem
        product: DesignSystem
      - package: UIComponents
        product: UIComponents
      - package: Utilities
        product: Utilities
      - package: DetectionKit
        product: DetectionKit
      - package: GameKitLS
        product: GameKitLS
      - package: VocabStore
        product: VocabStore
      - package: LLMKit
        product: LLMKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.langscape.app
        MARKETING_VERSION: 0.1.0
        CURRENT_PROJECT_VERSION: 1
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
