"""
Batch export of YOLO-World Core ML models for the 20 supported scene contexts.

Each context contains 50 high-priority vocabulary nouns. The script loads the
YOLOv8 World v2 student from Ultralytics, sets the class list, and exports an
INT8 CoreML package with NMS enabled.
"""

from pathlib import Path

from ultralytics import YOLOWorld


def main() -> None:
    print("Loading YOLO-World (v2 Small)...")
    model = YOLOWorld("yolov8s-worldv2.pt")

    contexts = {
        "Kitchen": [
            "fridge",
            "oven",
            "microwave",
            "sink",
            "dishwasher",
            "toaster",
            "kettle",
            "blender",
            "stove",
            "cabinet",
            "drawer",
            "plate",
            "bowl",
            "cup",
            "mug",
            "glass",
            "fork",
            "spoon",
            "knife",
            "pan",
            "pot",
            "lid",
            "spatula",
            "whisk",
            "ladle",
            "grater",
            "peeler",
            "cutting board",
            "colander",
            "apron",
            "napkin",
            "paper towel",
            "trash can",
            "sponge",
            "soap",
            "counter",
            "faucet",
            "freezer",
            "ice cube tray",
            "spice jar",
            "olive oil",
            "salt shaker",
            "pepper grinder",
            "coffee maker",
            "tea pot",
            "kitchen timer",
            "oven mitt",
            "tongs",
            "measuring cup",
            "rolling pin",
        ],
        "Living Room": [
            "sofa",
            "armchair",
            "coffee table",
            "television",
            "tv stand",
            "remote",
            "rug",
            "lamp",
            "cushion",
            "curtain",
            "blinds",
            "bookshelf",
            "fireplace",
            "mantel",
            "vase",
            "painting",
            "photo frame",
            "clock",
            "plant",
            "pot",
            "speaker",
            "candle",
            "coaster",
            "magazine",
            "book",
            "blanket",
            "throw pillow",
            "side table",
            "floor lamp",
            "ceiling fan",
            "light switch",
            "outlet",
            "window",
            "door",
            "wall",
            "carpet",
            "ottoman",
            "recliner",
            "bean bag",
            "console",
            "wifi router",
            "cable box",
            "dvd player",
            "video game console",
            "controller",
            "headset",
            "laptop",
            "tablet",
            "charger",
            "mirror",
        ],
        "Bedroom": [
            "bed",
            "mattress",
            "pillow",
            "duvet",
            "blanket",
            "sheet",
            "headboard",
            "nightstand",
            "alarm clock",
            "lamp",
            "wardrobe",
            "closet",
            "hanger",
            "drawer",
            "mirror",
            "dresser",
            "rug",
            "curtain",
            "blinds",
            "window",
            "slipper",
            "pajamas",
            "robe",
            "laundry basket",
            "trash can",
            "charger",
            "phone",
            "book",
            "glasses",
            "jewelry box",
            "perfume",
            "lotion",
            "tissue box",
            "teddy bear",
            "fan",
            "heater",
            "air conditioner",
            "light switch",
            "painting",
            "poster",
            "laptop",
            "desk",
            "chair",
            "shelf",
            "makeup",
            "comb",
            "brush",
            "sock",
            "shoe",
            "hat",
        ],
        "Bathroom": [
            "toilet",
            "sink",
            "bathtub",
            "shower",
            "shower curtain",
            "faucet",
            "mirror",
            "towel",
            "towel rack",
            "toilet paper",
            "plunger",
            "toilet brush",
            "soap",
            "shampoo",
            "conditioner",
            "body wash",
            "sponge",
            "loofah",
            "toothbrush",
            "toothpaste",
            "floss",
            "mouthwash",
            "razor",
            "shaving cream",
            "lotion",
            "deodorant",
            "comb",
            "hairbrush",
            "hair dryer",
            "straightener",
            "makeup",
            "lipstick",
            "mascara",
            "nail polish",
            "cotton ball",
            "q-tip",
            "trash can",
            "scale",
            "bath mat",
            "tile",
            "drain",
            "shelf",
            "cabinet",
            "medicine cabinet",
            "perfume",
            "cologne",
            "robe",
            "slipper",
            "rubber duck",
            "basket",
        ],
        "Office": [
            "desk",
            "office chair",
            "computer",
            "monitor",
            "keyboard",
            "mouse",
            "mousepad",
            "laptop",
            "tablet",
            "printer",
            "scanner",
            "copier",
            "shredder",
            "phone",
            "headset",
            "webcam",
            "microphone",
            "speaker",
            "lamp",
            "stapler",
            "staples",
            "tape",
            "tape dispenser",
            "scissors",
            "paperclip",
            "binder clip",
            "thumbtack",
            "corkboard",
            "whiteboard",
            "marker",
            "eraser",
            "pen",
            "pencil",
            "highlighter",
            "notebook",
            "notepad",
            "sticky note",
            "folder",
            "file cabinet",
            "trash can",
            "recycling bin",
            "calendar",
            "clock",
            "bookshelf",
            "book",
            "plant",
            "coffee mug",
            "water bottle",
            "backpack",
            "briefcase",
        ],
        "Classroom": [
            "desk",
            "chair",
            "table",
            "whiteboard",
            "blackboard",
            "chalk",
            "marker",
            "eraser",
            "projector",
            "screen",
            "computer",
            "laptop",
            "tablet",
            "bookshelf",
            "book",
            "textbook",
            "notebook",
            "binder",
            "folder",
            "paper",
            "pencil",
            "pen",
            "ruler",
            "eraser",
            "sharpener",
            "scissors",
            "glue",
            "tape",
            "stapler",
            "calculator",
            "globe",
            "map",
            "flag",
            "clock",
            "calendar",
            "poster",
            "chart",
            "trash can",
            "recycling bin",
            "backpack",
            "lunchbox",
            "water bottle",
            "teacher",
            "student",
            "uniform",
            "coat rack",
            "cubby",
            "locker",
            "speaker",
            "door",
        ],
        "Gym": [
            "treadmill",
            "elliptical",
            "stationary bike",
            "rowing machine",
            "dumbbell",
            "barbell",
            "weight plate",
            "kettlebell",
            "bench",
            "squat rack",
            "pull-up bar",
            "dip bar",
            "cable machine",
            "leg press",
            "yoga mat",
            "foam roller",
            "medicine ball",
            "stability ball",
            "jump rope",
            "resistance band",
            "punching bag",
            "boxing glove",
            "mirror",
            "scale",
            "water fountain",
            "water bottle",
            "shaker bottle",
            "towel",
            "locker",
            "lock",
            "bench",
            "shower",
            "sauna",
            "clock",
            "timer",
            "speaker",
            "fan",
            "chalk",
            "belt",
            "shoes",
            "sneakers",
            "shorts",
            "leggings",
            "tank top",
            "headband",
            "sweatband",
        "monitor",
        "tv",
        "gym bag",
        "trainer",
    ],
        "Park": [
            "bench",
            "tree",
            "bush",
            "flower",
            "grass",
            "path",
            "sidewalk",
            "trash can",
            "recycling bin",
            "lamp post",
            "fountain",
            "statue",
            "pond",
            "duck",
            "bird",
            "squirrel",
            "dog",
            "leash",
            "bicycle",
            "skateboard",
            "scooter",
            "stroller",
            "playground",
            "swing",
            "slide",
            "seesaw",
            "monkey bars",
            "sandbox",
            "picnic table",
            "grill",
            "gazebo",
            "pavilion",
            "restroom",
            "sign",
            "fence",
            "gate",
            "bridge",
            "rock",
            "stone",
            "cloud",
            "sun",
            "sky",
            "ball",
            "frisbee",
            "kite",
            "drone",
            "runner",
            "cyclist",
            "pedestrian",
            "car",
        ],
        "Supermarket": [
            "cart",
            "basket",
            "shelf",
            "aisle",
            "freezer",
            "fridge",
            "cash register",
            "conveyor belt",
            "scale",
            "scanner",
            "bag",
            "receipt",
            "produce",
            "fruit",
            "vegetable",
            "apple",
            "banana",
            "orange",
            "bread",
            "milk",
            "egg",
            "cheese",
            "meat",
            "chicken",
            "fish",
            "cereal",
            "rice",
            "pasta",
            "can",
            "jar",
            "bottle",
            "box",
            "price tag",
            "sign",
            "employee",
            "customer",
            "checkout",
            "kiosk",
            "money",
            "card",
            "wallet",
            "purse",
            "mop",
            "bucket",
            "broom",
            "display",
            "sample",
            "coupon",
            "flyer",
        ],
        "Cafe": [
            "table",
            "chair",
            "booth",
            "stool",
            "counter",
            "barista",
            "espresso machine",
            "coffee grinder",
            "blender",
            "kettle",
            "fridge",
            "display case",
            "pastry",
            "croissant",
            "muffin",
            "cake",
            "cookie",
            "sandwich",
            "salad",
            "menu",
            "board",
            "cup",
            "mug",
            "glass",
            "straw",
            "lid",
            "sleeve",
            "napkin",
            "sugar",
            "creamer",
            "stirrer",
            "spoon",
            "fork",
            "knife",
            "plate",
            "tray",
            "trash can",
            "recycling bin",
            "laptop",
            "wifi",
            "outlet",
            "plant",
            "painting",
            "light",
            "door",
            "window",
            "sign",
            "customer",
            "line",
            "register",
        ],
        "Restaurant": [
            "table",
            "chair",
            "booth",
            "tablecloth",
            "napkin",
            "silverware",
            "fork",
            "knife",
            "spoon",
            "plate",
            "bowl",
            "glass",
            "wine glass",
            "menu",
            "candle",
            "vase",
            "flower",
            "salt shaker",
            "pepper shaker",
            "waiter",
            "waitress",
            "chef",
            "host",
            "kitchen",
            "stove",
            "oven",
            "grill",
            "fridge",
            "sink",
            "tray",
            "stand",
            "check",
            "bill",
            "credit card",
            "terminal",
            "sign",
            "door",
            "window",
            "curtain",
            "light",
            "chandelier",
            "artwork",
            "restroom",
            "bar",
            "stool",
            "bottle",
            "cork",
            "bucket",
            "ice",
            "bread",
            "basket",
        ],
        "Street": [
            "car",
            "truck",
            "bus",
            "motorcycle",
            "bicycle",
            "scooter",
            "van",
            "taxi",
            "police car",
            "ambulance",
            "firetruck",
            "traffic light",
            "stop sign",
            "street sign",
            "crosswalk",
            "sidewalk",
            "curb",
            "road",
            "lane",
            "pavement",
            "manhole",
            "drain",
            "lamp post",
            "fire hydrant",
            "parking meter",
            "trash can",
            "mailbox",
            "newsstand",
            "bench",
            "tree",
            "building",
            "store",
            "window",
            "door",
            "pedestrian",
            "driver",
            "cyclist",
            "pigeon",
            "dog",
            "leash",
            "stroller",
            "umbrella",
            "rain",
            "puddle",
            "snow",
            "bridge",
            "tunnel",
            "fence",
            "wall",
            "graffiti",
        ],
        "Bus Station": [
            "bus",
            "stop",
            "shelter",
            "bench",
            "schedule",
            "map",
            "sign",
            "screen",
            "ticket machine",
            "ticket",
            "card reader",
            "turnstile",
            "platform",
            "curb",
            "lane",
            "driver",
            "passenger",
            "line",
            "luggage",
            "suitcase",
            "backpack",
            "purse",
            "trash can",
            "recycling bin",
            "lamp post",
            "camera",
            "speaker",
            "announcement",
            "clock",
            "roof",
            "pillar",
            "wall",
            "window",
            "door",
            "wheel",
            "tire",
            "mirror",
            "wiper",
            "headlight",
            "taillight",
            "number",
            "destination",
            "seat",
            "handle",
            "pole",
            "bell",
            "button",
            "card",
            "pass",
            "kiosk",
        ],
        "Train Station": [
            "train",
            "tracks",
            "platform",
            "bench",
            "ticket machine",
            "ticket",
            "turnstile",
            "gate",
            "screen",
            "schedule",
            "clock",
            "sign",
            "map",
            "escalator",
            "stairs",
            "elevator",
            "tunnel",
            "bridge",
            "roof",
            "column",
            "light",
            "camera",
            "speaker",
            "announcement",
            "kiosk",
            "shop",
            "cafe",
            "vending machine",
            "trash can",
            "recycling bin",
            "passenger",
            "conductor",
            "guard",
            "luggage",
            "suitcase",
            "backpack",
            "bicycle",
            "wheelchair",
            "stroller",
            "rail",
            "sleeper",
            "gravel",
            "electric line",
            "pantograph",
            "locomotive",
            "wagon",
            "door",
            "window",
            "seat",
            "handle",
        ],
        "Airport": [
            "airplane",
            "runway",
            "gate",
            "terminal",
            "check-in",
            "counter",
            "kiosk",
            "screen",
            "schedule",
            "luggage",
            "suitcase",
            "bag",
            "conveyor belt",
            "security",
            "scanner",
            "tray",
            "passport",
            "ticket",
            "boarding pass",
            "pilot",
            "flight attendant",
            "passenger",
            "seat",
            "window",
            "cart",
            "wheelchair",
            "stroller",
            "escalator",
            "moving walkway",
            "elevator",
            "stairs",
            "shop",
            "restaurant",
            "cafe",
            "restroom",
            "sign",
            "clock",
            "announcement",
            "speaker",
            "control tower",
            "tarmac",
            "bus",
            "truck",
            "fuel truck",
            "stairs truck",
            "cone",
            "vest",
            "badge",
            "metal detector",
            "x-ray",
        ],
        "Hospital": [
            "bed",
            "stretcher",
            "wheelchair",
            "walker",
            "crutches",
            "cane",
            "doctor",
            "nurse",
            "surgeon",
            "patient",
            "scrubs",
            "coat",
            "mask",
            "gloves",
            "stethoscope",
            "thermometer",
            "monitor",
            "screen",
            "iv stand",
            "drip",
            "needle",
            "syringe",
            "bandage",
            "cast",
            "medicine",
            "pill",
            "bottle",
            "tray",
            "cart",
            "ambulance",
            "siren",
            "light",
            "sign",
            "reception",
            "desk",
            "computer",
            "phone",
            "chair",
            "waiting room",
            "magazine",
            "tv",
            "elevator",
            "stairs",
            "door",
            "hallway",
            "room",
            "curtain",
            "sink",
            "soap",
            "sanitizer",
        ],
        "Library": [
            "bookshelf",
            "book",
            "magazine",
            "newspaper",
            "desk",
            "table",
            "chair",
            "armchair",
            "computer",
            "monitor",
            "keyboard",
            "mouse",
            "printer",
            "scanner",
            "copier",
            "librarian",
            "patron",
            "card",
            "scanner",
            "cart",
            "stairs",
            "elevator",
            "lamp",
            "light",
            "window",
            "door",
            "carpet",
            "quiet sign",
            "poster",
            "bulletin board",
            "clock",
            "plant",
            "trash can",
            "recycling bin",
            "outlet",
            "wifi",
            "headphone",
            "tablet",
            "ebook",
            "audiobook",
            "cd",
            "dvd",
            "catalog",
            "index",
            "pen",
            "pencil",
            "paper",
            "notebook",
            "backpack",
            "bag",
        ],
        "Clothing Store": [
            "rack",
            "shelf",
            "hanger",
            "mannequin",
            "mirror",
            "fitting room",
            "curtain",
            "bench",
            "counter",
            "register",
            "cashier",
            "customer",
            "bag",
            "receipt",
            "tag",
            "sign",
            "sale",
            "shirt",
            "t-shirt",
            "blouse",
            "sweater",
            "hoodie",
            "jacket",
            "coat",
            "pants",
            "jeans",
            "shorts",
            "skirt",
            "dress",
            "suit",
            "tie",
            "belt",
            "hat",
            "cap",
            "beanie",
            "scarf",
            "gloves",
            "sock",
            "shoe",
            "sneaker",
            "boot",
            "sandal",
            "heel",
            "underwear",
            "bra",
            "swimsuit",
            "jewelry",
            "watch",
            "glasses",
            "sunglasses",
        ],
        "Bakery": [
            "bread",
            "baguette",
            "roll",
            "bun",
            "croissant",
            "danish",
            "muffin",
            "scone",
            "donut",
            "bagel",
            "cake",
            "slice",
            "pie",
            "tart",
            "cookie",
            "brownie",
            "pastry",
            "cupcake",
            "display case",
            "tray",
            "tongs",
            "bag",
            "box",
            "napkin",
            "menu",
            "price tag",
            "sign",
            "baker",
            "apron",
            "hat",
            "oven",
            "mixer",
            "bowl",
            "flour",
            "sugar",
            "dough",
            "rolling pin",
            "cutter",
            "table",
            "chair",
            "counter",
            "register",
            "coffee",
            "tea",
            "milk",
            "juice",
            "customer",
            "window",
            "door",
            "smell",
        ],
        "Pharmacy": [
            "counter",
            "register",
            "pharmacist",
            "technician",
            "customer",
            "prescription",
            "pill",
            "tablet",
            "capsule",
            "bottle",
            "jar",
            "box",
            "blister pack",
            "medicine",
            "vitamin",
            "supplement",
            "shelf",
            "aisle",
            "cart",
            "basket",
            "crutches",
            "cane",
            "walker",
            "wheelchair",
            "brace",
            "bandage",
            "band-aid",
            "gauze",
            "tape",
            "thermometer",
            "mask",
            "gloves",
            "sanitizer",
            "soap",
            "shampoo",
            "conditioner",
            "lotion",
            "cream",
            "ointment",
            "toothpaste",
            "toothbrush",
            "floss",
            "mouthwash",
            "razor",
            "shaving cream",
            "makeup",
            "candy",
            "drink",
            "magazine",
            "card",
        ],
    }

    output_dir = Path("exported_models")
    output_dir.mkdir(parents=True, exist_ok=True)

    for context_name, vocabulary in contexts.items():
        print(f"Exporting context: {context_name} ({len(vocabulary)} words)...")
        model.set_classes(vocabulary)
        filename = f"yolo_world_{context_name.lower().replace(' ', '_')}"
        result = model.export(
            format="coreml",
            int8=True,
            nms=True,
            project=str(output_dir),
            name=filename,
        )
        if result:
            print(f"✅ Successfully exported {context_name}")
        else:
            print(f"❌ Failed to export {context_name}")

    print("🎉 All contexts exported!")


if __name__ == "__main__":
    main()
